{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "picolors.serviceAccountName" . }}
  labels:
{{ include "picolors.labels" . | nindent 4 }}
{{- end -}}
