apiVersion:  v1
kind: ConfigMap
metadata: 
  name: {{ template "echo-server.fullname" . }}
data: 
    PORT: {{ .Values.service.port  | quote }}
    LOGS__IGNORE__PING: {{ .Values.application.logs.ignore.ping  | quote }}
    ENABLE__HOST: {{ .Values.application.enable.host  | quote }}
    ENABLE__HTTP: {{ .Values.application.enable.http  | quote }}
    ENABLE__REQUEST: {{ .Values.application.enable.request  | quote }}
    ENABLE__COOKIES: {{ .Values.application.enable.cookies  | quote }}
    ENABLE__ENVIRONMENT: {{ .Values.application.enable.environment  | quote }}
    ENABLE__FILE: {{ .Values.application.enable.file  | quote }}
    ENABLE__HEADER: {{ .Values.application.enable.header  | quote }}
