{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "echo-server.serviceAccountName" . }}
  labels: {{- include "echo-server.labels" . | nindent 4 }}
{{- end -}}
