name: Helm Lint

on:
  pull_request:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: azure/setup-helm@v4
    - name: Lint charts
      run: helm lint --strict ./charts/*
