name: Helm Publish

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: J12934/helm-gh-pages-action@master
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: "gh-pages"
          charts-folder: "charts"
